language: python
python:
- 3.5
- 2.7
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements.txt
- pip install -r tests/requirements.txt
script:
- ./scripts/run_tests.sh
after_success:
- ./scripts/travis_deploy.sh
branches:
  except:
    - /^v[0-9]/
env:
  global:
  - secure: Lm+Z5fdILpn6IQX/NeVLTFoHjFTg5zdNU2ki7ACoqxlLcOmIeaESo4WvvfCmSqJq7XhwHPIDvv3aznuveULaknK7Y1XinDBdBikgWKyNrPv7AjS3ltxo8VOhl8mkWRPZPU0ZXFuFZeYglkD3eudN93aZF3ddDqKLCjhGd52dzsbkBIEVlResGjHp1rfbEKxAb3qX34j1TYMfCdzlt0FUifEiaoKL91YrRxq0PfYfNEvEBSSm2EkCJCUleaIDB2SFiBHoj6dCPwRUxmXFliHyH3YsCuGxBhGJT+ATNh+FNmUd6H3uL9w69D5LppiEGdCy5yvF+SfgKFiAUOOvrG2RJAQ+aY7fblfevLzy2Pm6MD0UyyS+oEchF9SzXEwnDu5Y4+Q5wz58ZQygjSr8d03wKZY76fkfK4VqpjZG5Pg3pgPNlCVfsNzvwVZ0w+WUh5HU5D1afkPd6NECi4KcWjTbqG/L3zAr0rv6T38eAgvngzP9/aX+h0AdWra0ycFsvRIIdFN+tjxn9G8Cz4eGMpLYlvcd4EsBiaZajM41WC045wKvwIesFENu2RaejorOahuIt4Hk3GgoS/99hi9DWVEGISs6J/NwVUyFIvfmZPxi2PMdgW02VIQCD7ZDlc5ZzAk7El9dwcB4D3r2CvxZCKoUBvaOEaoTZ12n/kBvcScZUTI=
  - secure: wuZpOV7GGsQqMiaEmBZdqy7EGoRknV8K/OuxvS/SHfZpMTBr6dPi+C6Anr/onSE30ibLARkG3j9YOvOoJaRnw4vkQkHnE6L7C7J5Bh/m812j1aiNqf/6nLME8wN63hPw/eILfMqquQivWf3thC/YT+6W6vJYMQ220mcAcE6YeA5wFC4YbAAQ+IYkMovu7qdzQZENshNjHoA4Eh8CI3Lgm8brK+wG8Yb4J9uqJmGc20lSmC86WUVWsz3dnPROU8GeBvwgFMLqm1n1/wT0rfGtlzfbenUGa2vL42C1go+7c4F/Ajex8kRWcIrFdNpal8b6Qeo8nXCVXaU1x9eMLTft7D+7jy+bZybaww2FEXRtbobhSaXTI19aHQtKgh4UGoM175RcSaCWlTg+TvY1yyyFWm4Qio88I3aety7p3u9ueG8cJSh7TVCZMcZveYS5Z7sIH3lA1Qiz/UUA2AefH0Au8yAUAhxFQs4ayXoYOvaJcI6fDu3gCoer3MoIiDjVd8W+chWoCV+3J+KKo6KYOfLhcNIg3ywm0mgLbJcI+B/DQCkurVZo9Sb1TdrX6AG6H+4mWmeaDwdOIqf/Z933ymZFMWH8n6U6hv0/FioNfJVy41mJu7G+/iEnptmHw5uLjK5o8wA0tCPDqXQOwXLKhhTG/CL5Buf7o3n4cJVOYI9UFTA=
