sudo: required
services:
- docker
addons:
  apt:
    packages:
    - python3
    - python3-pip
before_install:
  - sudo pip3 install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install -e .
script:
  - invoke test

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: W74heVJlSkSJrYY4YBBcv1bKZrK7f0FGGK0IXZ3iqt3VYuWiDV8Bn9mitqAlYsGT+qiPTj/zeQsxJk19NDqBWUFr1l/pDKcPUyUIdORKV19uvvKZVqwp+bR0fbugA33rodmihuwYLZE1tHEFziZIVzlyRHP3x0zj8I1cpRsCjw1Uq8aRtJCXPoUOH/JKKpFSTWHFJMhJfCJZDEqWM8s7Vko/PVCw97FLW/qT/+MyQgQ0JqPru/9sjlGsSy2pIlsWE4Xs0qY9/Fr/1j4WpHysU5f729TrsoAlZuRbH2A3tWjpPrj6HAoPn0GmmJK7Ju2t62kBmlpdm/jonVLgiA1740s8V23Ru9X9f4GiSZRDsZumn69p9vdSvPHK9So8jzmsFbTKqb7yNABwqXdyZLFiiim75Q09pJglb8gifWJRGQXe7h2e1FYsSeEQ5gx6zTiuoDmc760PZjhQJ6EqLTlhIf9hVrt+gqbb9/QMkQAIRvi3Ru4gGNMIZVWYb/noWlrfx1pa99DY6vYXsvxmFrXiKJM3KJDtQyU+/ybE4lHtFkBrlwjZ59HS5yL0gGberVzgW3k37Dqktx+ziiP2C66wOTKqYm2Ob29Or3reO5fATs+ZcsEZeruzDTmJN2p2pbqZLQ6LRqNRKNAYfJeOk5Eg5UHu6jeZt5KYtAhSrLHPxi8=
    # AWS_SECRET_ACCESS_KEY
    - secure: 04PQIHj5GfFj0fXHTWuz5DXk5Ac3ATRYKnFDSb66NC2czIvex5RqWjSUXG7UJZ/ltUo8xlxAz1Y7/30HzJ4q7uk0wmjbcGn+QyAOpIwYbttTMWvI6d3cP+ihRuqoDH3vphpiIUwWEfkuw2f27e5HV8xdiyMMwbSv69y+KbxVvjeYMcSbEvyWmctQMK+Ihb9vgFiNZs/sZvu/mO6f3hVq4fk3FmB5UA+GEHz6mqsXAtKR0DLV7OD0L+54q9hVECRSe1vGKqOAWY8uSz8Lln5kI+eus332AbzAmJ4i/Wko6zeHN+8blR1c+PScGIAhN450Gv0m5x1NheKYEgc1HXHucr2/wavXlDvgsw/J+GMxAWnPo/bZY5oVltJiuwjx+uVA1Y0EFbTwn6XfMT84bZpTWUfydLP37yx3XfegjYVc1h7UlVABowxkH9SOwnkSqM+Co2g4I1uLC2iYx/moJMOf/PVBbnWlrEir8p70zjVKN71ABFYb0qcE/cFz1B6CVTJcLhxJ3K49yJBZgQ29sbhLGfE7RA8+OWGG5uY+fpQoPgRqSn/vcxgqPgUfhuk0txX47B8VwBTerzG1ehQkr2ib94q4grmN1pG+D4nHTkZMEU7LfxQRLih+/XvPXRsuxh0A4I5OYouERMxoiiAG7H3L1JBG2kaIMUqSk1FQR6gy6Bo=
